//File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcZGmPSpNkbY34zIueoTT1GVuPHK-iaiE',
    appId: '1:739294200651:web:17eb68e199c54f876e5ece',
    messagingSenderId: '739294200651',
    projectId: 'hazirapp-6bc77',
    authDomain: 'hazirapp-6bc77.firebaseapp.com',
    storageBucket: 'hazirapp-6bc77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe811x2wOUO-VZwv1BmEpE-te-TjI9UtU',
    appId: '1:739294200651:android:4a982e333a564fdb6e5ece',
    messagingSenderId: '739294200651',
    projectId: 'hazirapp-6bc77',
    storageBucket: 'hazirapp-6bc77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEYn61piVtEARBxXvbsjSMyVAcFDo69JE',
    appId: '1:739294200651:ios:8e2e07d4c3d3dc296e5ece',
    messagingSenderId: '739294200651',
    projectId: 'hazirapp-6bc77',
    storageBucket: 'hazirapp-6bc77.firebasestorage.app',
    androidClientId: '739294200651-67vcnrr91otke4eh4meqtj8q1pv5s628.apps.googleusercontent.com',
    iosClientId: '739294200651-dk7ksufie18iqvtaqi0hu6po96fvknii.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEYn61piVtEARBxXvbsjSMyVAcFDo69JE',
    appId: '1:739294200651:ios:8e2e07d4c3d3dc296e5ece',
    messagingSenderId: '739294200651',
    projectId: 'hazirapp-6bc77',
    storageBucket: 'hazirapp-6bc77.firebasestorage.app',
    androidClientId: '739294200651-67vcnrr91otke4eh4meqtj8q1pv5s628.apps.googleusercontent.com',
    iosClientId: '739294200651-dk7ksufie18iqvtaqi0hu6po96fvknii.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcZGmPSpNkbY34zIueoTT1GVuPHK-iaiE',
    appId: '1:739294200651:web:b9a83e30d142f0446e5ece',
    messagingSenderId: '739294200651',
    projectId: 'hazirapp-6bc77',
    authDomain: 'hazirapp-6bc77.firebaseapp.com',
    storageBucket: 'hazirapp-6bc77.firebasestorage.app',
  );

}